# fly.toml app configuration file generated for piss on 2024-01-25T09:16:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'piss'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[[mounts]]
  source = 'storage'
  destination = '/rails/storage'

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
